name: Code Review GPT CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci

      - name: Run code review script
        run: npx code-review-gpt --ci
