name: 'Code Review GPT'
description: 'A description of what your action does.'
author: 'Orion Tools'
inputs:
  MODEL:
    description: 'The GPT model to use'
    required: true
    default: 'gpt-3.5-turbo'
  OPENAI_API_KEY:
    description: 'OpenAI API Key'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install code-review-gpt dependencies
      shell: bash
      run: cd code-review-gpt && npm ci
    
    - name: Run Code Review GPT
      shell: bash
      run: npm run start -- --ci=github --model=gpt-3.5-turbo
      # run: npx ts-node ./src/index.ts -- --ci=github --model=$MODEL

    # - name: Install & add code-review-gpt to CI
    #   shell: bash
    #   run: |
    #     npm install code-review-gpt
    #     npx code-review-gpt configure --setupTarget=github
      
      env:
        MODEL: ${{ inputs.MODEL }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
