stages:
  - build

variables:
  GIT_DEPTH: 0

default:
  image: node

build-job:
  stage: build
  script:
    - npm ci
    - npm install code-review-gpt
    - npx code-review-gpt review --ci=gitlab
  rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
