stages:
  - build
  - test

default:
  image: node

build-job:
  stage: build
  script:
    - npm ci
    - npm run build
    - npm run start-gitlab
  rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

unit-test-job:
  stage: test
  script:
    - npm ci
    - npm run build
    - npm run test-ci-gitlab
  rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
