name: Test My Custom Action

on:
  push:
    branches:
      - feat/github-marketplace-action
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use My Custom Action
        uses: ../action.yml # Reference your custom action directory
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: 'gpt-3.5-turbo'
